# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by an overlay under config/overlays/
resources:
- bases/inventory.miloapis.com_regions.yaml
- bases/inventory.miloapis.com_providers.yaml
- bases/inventory.miloapis.com_sites.yaml
- bases/inventory.miloapis.com_racks.yaml
- bases/inventory.miloapis.com_clusters.yaml
- bases/inventory.miloapis.com_nodes.yaml
- bases/inventory.miloapis.com_networkdevices.yaml
- bases/inventory.miloapis.com_ports.yaml
- bases/inventory.miloapis.com_cables.yaml
- bases/inventory.miloapis.com_circuits.yaml
- bases/inventory.miloapis.com_links.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
