apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: inventory.miloapis.com-cable
spec:
  serviceRef:
    name: "inventory.miloapis.com"
  kind: Cable
  plural: cables
  singular: cable
  subresources:
    - name: status
      permissions:
        - get
        - update
        - patch
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
