apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: inventory.miloapis.com-circuit
spec:
  serviceRef:
    name: "inventory.miloapis.com"
  kind: Circuit
  plural: circuits
  singular: circuit
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
