apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: inventory.miloapis.com-cluster
spec:
  serviceRef:
    name: "inventory.miloapis.com"
  kind: Cluster
  plural: clusters
  singular: cluster
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
