apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: graph.inventory.miloapis.com-edge
spec:
  serviceRef:
    name: "graph.inventory.miloapis.com"
  kind: Edge
  plural: edges
  singular: edge
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
