apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: graph.inventory.miloapis.com-edgetype
spec:
  serviceRef:
    name: "graph.inventory.miloapis.com"
  kind: EdgeType
  plural: edgetypes
  singular: edgetype
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
