apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: inventory.miloapis.com-networkdevice
spec:
  serviceRef:
    name: "inventory.miloapis.com"
  kind: NetworkDevice
  plural: networkdevices
  singular: networkdevice
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
