apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: inventory.miloapis.com-node
spec:
  serviceRef:
    name: "inventory.miloapis.com"
  kind: Node
  plural: nodes
  singular: node
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
