apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: inventory.miloapis.com-provider
spec:
  serviceRef:
    name: "inventory.miloapis.com"
  kind: Provider
  plural: providers
  singular: provider
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
