apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: inventory.miloapis.com-site
spec:
  serviceRef:
    name: "inventory.miloapis.com"
  kind: Site
  plural: sites
  singular: site
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
