apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: inventory.miloapis.com-virtualmachine
spec:
  serviceRef:
    name: "inventory.miloapis.com"
  kind: VirtualMachine
  plural: virtualmachines
  singular: virtualmachine
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
