apiVersion: inventory.miloapis.com/v1alpha1
kind: VirtualMachine
metadata:
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachine-sample
spec:
  hostRef:
    name: node-sample
  providerRef:
    name: provider-sample
  projectRef:
    apiGroup: resourcemanager.miloapis.com
    kind: Project
    name: my-project
  allocation:
    vcpus: 4
    memoryBytes: 17179869184
    disks:
      - name: root
        sizeBytes: 107374182400
        type: SSD
