apiVersion: inventory.miloapis.com/v1alpha1
kind: Node
metadata:
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/managed-by: kustomize
  name: node-sample
spec:
  siteRef:
    name: site-sample
  hardware:
    cpuCores: 8
    cpuArchitecture: amd64
    memoryBytes: 34359738368
    disks:
      - name: nvme0n1
        sizeBytes: 1099511627776
        type: NVMe
  addresses:
    - type: Internal
      address: 10.0.1.10
    - type: Hostname
      address: node-sample.us-east-1a.inventory.example.com
  assignment:
    clusterRef:
      name: cluster-sample
    role: Worker
