apiVersion: inventory.miloapis.com/v1alpha1
kind: Link
metadata:
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/managed-by: kustomize
  name: link-sample
spec:
  endpoints:
    - kind: Site
      name: site-sample
    - kind: Cluster
      name: cluster-sample
  type: Physical
  capacityMbps: 40000
  latencyMs: "1"
