apiVersion: inventory.miloapis.com/v1alpha1
kind: Provider
metadata:
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/managed-by: kustomize
  name: provider-sample
spec:
  displayName: Equinix
  type: Colocation
  contract:
    contractID: EQ-12345
    accountID: 987654
    portalURL: https://portal.equinix.com
    notes: Primary colo provider for US East
  serviceIdentifiers:
    - name: IBX
      identifier: DC11
