apiVersion: inventory.miloapis.com/v1alpha1
kind: NetworkDevice
metadata:
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/managed-by: kustomize
  name: networkdevice-sample
spec:
  clusterRef:
    name: cluster-sample
  siteRef:
    name: site-sample
  role: Leaf
  managementAddress: 10.0.0.2
