apiVersion: inventory.miloapis.com/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/managed-by: kustomize
  name: cluster-sample
spec:
  displayName: us-east-1a-compute-01
  controlPlaneSiteRef:
    name: site-sample
  role: Compute
  provider: sidero-omni
  endpoint: https://cluster-sample.inventory.example.com:6443
