apiVersion: inventory.miloapis.com/v1alpha1
kind: Region
metadata:
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/managed-by: kustomize
  name: region-sample
spec:
  displayName: US East
  coordinates:
    latitude: 37.5
    longitude: -77.5
