apiVersion: inventory.miloapis.com/v1alpha1
kind: Site
metadata:
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/managed-by: kustomize
  name: site-sample
spec:
  displayName: US East 1A
  regionRef:
    name: region-sample
  type: Datacenter
  address: 21715 Filigree Ct, Ashburn, VA 20147
