apiVersion: inventory.miloapis.com/v1alpha1
kind: Cable
metadata:
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/managed-by: kustomize
  name: cable-sample
spec:
  endpoints:
    - name: port-sample
    - name: port-sample-far-end
  media: FiberSMF
  lengthM: "3"
  label: A14-pp-A-01
